sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: YuanRui20050614
  alioss:
    bucket-name: yr-sky-take-out
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5t9wHCiGw2w59NbqPARz
    access-key-secret: qpMGsyvZvq4FhzDXGpTpYwTfgksM63
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxa9b91b290f6df02e
    secret: e15db77a6eef2f731a724a1fd7966ecf
    mchid: 1561414331
    mch-serial-no: 4B3BDC35414AD50B1B755BAF8DE9CC7CF407606
    private-key-file-path:
    api-v3-key: CZBK51236435wxpay435434323FFDuv3
    we-chat-pay-cert-file-path:
    notify-url: https://51125741.r18.cpolar.top/notify/paySuccess
    refund-notify-url: https://51125741.r18.cpolar.top/notify/paySuccess
  shop:
    address: 四川省成都市成华区建设北路二段四号
    ak: jG5tckCUudBGh5RkQL1t00mma8SKysE6
