sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: YuanRui20050614
  alioss:
    bucket-name: yr-sky-take-out
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5t9wHCiGw2w59NbqPARz
    access-key-secret: qpMGsyvZvq4FhzDXGpTpYwTfgksM63
